/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tragaperras;

/**
 *
 * @author josef
 */
public class MaquinaPrin extends javax.swing.JFrame {

    /**
     * Creates new form MaquinaPrin
     */
    public MaquinaPrin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPalanca = new javax.swing.JButton();
        labelUno = new javax.swing.JLabel();
        labelDos = new javax.swing.JLabel();
        labelTres = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPalanca.setText("PALANCA");
        btnPalanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalancaActionPerformed(evt);
            }
        });

        labelUno.setBackground(new java.awt.Color(153, 204, 255));
        labelUno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelUno.setForeground(new java.awt.Color(0, 51, 255));
        labelUno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUno.setText("X");

        labelDos.setBackground(new java.awt.Color(153, 204, 255));
        labelDos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelDos.setForeground(new java.awt.Color(0, 51, 255));
        labelDos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDos.setText("X");

        labelTres.setBackground(new java.awt.Color(153, 204, 255));
        labelTres.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTres.setForeground(new java.awt.Color(0, 51, 255));
        labelTres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTres.setText("X");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelUno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(labelDos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(labelTres, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPalanca, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUno)
                    .addComponent(labelDos)
                    .addComponent(labelTres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnPalanca, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalancaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPalancaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalanca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDos;
    private javax.swing.JLabel labelTres;
    private javax.swing.JLabel labelUno;
    // End of variables declaration//GEN-END:variables
}
